spring:
  application:
    name: zuul-gateway

server:
  port: 30111

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8401/eureka/, http://peer2:8402/eureka/, http://peer2:8402/eureka/
  instance:
    instance-id: zuul-gateway # \u914D\u7F6E\u670D\u52A1\u540D\u79F0

zuul:
  host:
    maxTotalConnections: 2000
    maxPerRouteConnections: 800
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  semaphore:
    maxSemaphores: 1500
  routes:
    service-consumer:
      path: /consumer/**
      serviceId: service-consumer
    service-provider:
      path: /provider/**
      serviceId: service-provider