server:
  port: 8081

spring:
  application:
    name: service-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # \u914D\u7F6E\u6CE8\u518C\u4E2D\u5FC3
  instance:
    instance-id: hzm-service-consumer # \u914D\u7F6E\u670D\u52A1\u540D\u79F0